### ISSUE TITLE
Load from WAV not working

### ISSUE THREAD

**Issue by Wanstey110** [IanWraith/Rivet#2]
Hey there, I'm on a MacBook Air 2017 running MacOS. My XPA2 wav file loads in and it says "WAV file loaded and analysis complete (947072 samples read)" but after that nothing happens. The input level goes to full but that's it. I waited 10 minutes and still nothing happened (the audio file is 1 minute and 44 seconds). Any ideas/ suggestions?

**Comment by IanWraith** [comment]
Hard to say I'm afraid. Rivet would give an error if the sample rate was incorrect so its not that. It is possible the WAV is encoded in some way Rivet can't cope with. Another possibility is that Rivet can't find the XPA2 syncronisation sequence which it depends on to decode the message. 
Sorry I can't help more.

**Comment by Wanstey110** [comment]
Alright, thanks for the suggestion.
