### ISSUE TITLE
Compiling and starting issues

### ISSUE THREAD

**Issue by kord1e** [IanWraith/Rivet#3]
A quick report in case this program is still being developed:

1) This github repository doesn't seem to contain any build scripts or instructions, I think most people won't be able to build the software themselves.

2) The source package from signalshed.com contains a Gradle build script. It didn't work with Java 19, 17 or 11 because it complained that Java version can't be determined. It worked with Java 8 which is old but is still provided by several Linux distros.

However, the JAR file that was produced did not work - it complained about class paths not found or something. I already forgot the exact error messages but I can try again if it's useful. The file was also smaller than the pre-built file.

3) The pre-built file from signalshed.com (build 90) didn't work on Fedora but worked on Debian, I used Java 8.

**Comment by IanWraith** [comment]
Hello

I'm afraid I no longer have the time to support Rivet.

Basically updates to Java mean that much of the audio and threading code needs to be re written.

Sorry about that.

Ian
